### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RebeccaLarge1** [wattiau-rg/wattiau-rg.github.io#1]
- [ ] Change title of reception to evening for evening site
- [ ] Add dietary requirement sentence to reception pages
- [ ] Mention canapés in day reception pages

**Comment by wattiau-rg** [comment]
- [X] Change title of reception to evening for evening site
- [X] Add dietary requirement sentence to reception pages
- [X] Mention canapés in day reception pages
